SELECT  OI.PRODUCT_ID AS  fgk_prd, P.ID AS PRODUCT_ID, OI.ORDER_ID AS FGK_ORD,O.ID as ORDER_ID,  P.name, O.ORDER_STATUS, OI.QUANTITY, OI.PRICE

FROM TB_PRODUCT AS P
JOIN TB_ORDER_ITEM AS OI ON P.id = OI.PRODUCT_ID
JOIN TB_ORDER AS O ON O.id = OI.ORDER_ID;



